### ISSUE TITLE
SetShape on an existing etensor does not set column major

### ISSUE THREAD

**Issue by rohrlich** [emer/etable#2]
I cloned an etensor and then called SetShape on it changing shape and also the strides using ColMajorStrides. The shape was changed but "IsColMajor" returns false afterwards.

The same scenario on a new etensor did return true for IsColMajor().

**Comment by rcoreilly** [comment]
is this still a valid bug?

**Comment by rohrlich** [comment]
I'll test tonight

**Comment by rohrlich** [comment]
Yes still a bug, here is my test code:

	tsr := etensor.New(etensor.INT16, []int{4,5}, nil, nil)
	newtsr := tsr.Clone()
	newtsr.SetShape([]int{5,4}, []int{4,1}, nil)
	if newtsr.IsColMajor() {
		fmt.Println("yes is col major!")
	}

**Comment by rcoreilly** [comment]
well I've never tested anything to do with col major so there easily could be a bug -- could you look into it and fix anything you find.  it is all pretty clear in etensor what IsColMajor does -- just compares stride to what it would compute, so it should be easy to see what's wrong.

**Comment by rohrlich** [comment]
Yes still valid, here is my test code:

	tsr := etensor.New(etensor.INT16, []int{4,5}, nil, nil)
	newtsr := tsr.Clone()
	newtsr.SetShape([]int{5,4}, []int{4,1}, nil)
	if newtsr.IsColMajor() {
		fmt.Println("yes is col major!")
	}

**Comment by rohrlich** [comment]
Sure but I might not get to until 12/26.

**Comment by rohrlich** [comment]
Closing - not a bug. The strides I passed in were wrong! Next time I'll call ColMajorStrides() rather than trying to figure them out myself.
