### ISSUE TITLE
ePlot naming suggestions

### ISSUE THREAD

**Issue by rohrlich** [emer/etable#21]
Plot All -> Unfilter (Plot All suggests plotting all the variables and it is a no-op if you haven't filtered so it can be puzzling. Of course people should read the description but still Unfilter would be very clear)

Config -> Config...

Open CSV... -> Open Data... (Seems like at least csv and tsv are handled - unless you think csv is considered a generic term for all separated value data files, I don't know)

**Comment by rcoreilly** [comment]
In the Go world, CSV is treated as a generic term -- delimiter is a param.  I think that is also true more broadly to some extent.  I'm averse to the use of the term "Data" at this point :)

**Comment by rcoreilly** [comment]
rest done.
